export const initialState = {
  items: [
    // {
    //   id: "What_ajjaa",
    //   username: "jay",
    //   link: "add_tags_for_solutions",
    //   title: "Add tags for solutions",
    //   detail: "Easier to search for solutions based on a specific stack.",
    //   category: "Enhancement",
    //   vote: 17,
    //   voted: false,
    //   status: "suggestion",
    //   comments: [
    //     {
    //       id: "abcd_abc",
    //       username: "11gg Moss",
    //       avatar: "image-jay.jpg",
    //       user_id: "@hexagon.bestagon",
    //       comment: "this is comment",
    //       replies: [
    //         {
    //           id: "zAcds_as",
    //           username: "1-1Georrge random",
    //           avatar: "image-george.jpg",
    //           user_id: "@george.johnson",
    //           comment: "this is another  comment comment",
    //         },
    //         {
    //           id: "sadio_ASD",
    //           username: "1-2james dulex",
    //           avatar: "image-jay.jpg",
    //           user_id: "@james.christina",
    //           comment: "comment comment comment",
    //         },
    //         {
    //           id: "sadio_GG",
    //           username: "1-2james dulex",
    //           avatar: "image-jay.jpg",
    //           user_id: "@james.christina",
    //           comment: "This is not a comment",
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   id: "asd_asdASD",
    //   username: "jay",
    //   link: "2_tags_for_solutions",
    //   title: "2 tags for solutions",
    //   detail: "Easier to search for solutions based on a specific stack.",
    //   category: "UI",
    //   vote: 22,
    //   voted: false,
    //   status: "suggestion",
    //   comments: [
    //     {
    //       id: "gh_asdASDds",
    //       username: "22gg Moss",
    //       avatar: "image-george.jpg",
    //       user_id: "@hexagon.bestagon",
    //       comment: "this is comment",
    //       replies: [
    //         {
    //           id: "AcasA_sdjsd",
    //           username: "2-1Georrge random",
    //           avatar: "image-george.jpg",
    //           user_id: "@george.johnson",
    //           comment: "this is another  comment comment",
    //         },
    //         {
    //           id: "OVP_JQIsasd",
    //           username: "2-2james dulex",
    //           avatar: "image-james.jpg",
    //           user_id: "@james.christina",
    //           comment: "comment comment comment",
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   id: "asdisdAa_jdjf",
    //   username: "jay",
    //   link: "3_tags_for_solutions",
    //   title: "3 tags for solutions",
    //   detail: "Easier to search for solutions based on a specific stack.",
    //   category: "UX",
    //   vote: 19,
    //   voted: false,
    //   status: "suggestion",
    //   comments: [
    //     {
    //       id: "asdjvn_fdn",
    //       username: "33gg Moss",
    //       avatar: "image-george.jpg",
    //       user_id: "@hexagon.bestagon",
    //       comment: "this is comment",
    //       replies: [
    //         {
    //           id: "FsdADaf",
    //           username: "3-2james dulex",
    //           avatar: "image-james.jpg",
    //           user_id: "@james.christina",
    //           comment: "comment comment comment",
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   id: "What_acxvDSa",
    //   username: "jay",
    //   link: "4_tags_for_solutions",
    //   title: "4 tags for solutions",
    //   detail: "Easier to search for solutions based on a specific stack.",
    //   category: "Bug",
    //   vote: 44,
    //   voted: false,
    //   status: "suggestion",
    //   comments: [
    //     {
    //       id: "dsds_asdFG",
    //       username: "44gg Moss",
    //       avatar: "image-george.jpg",
    //       user_id: "@hexagon.bestagon",
    //       comment: "this is comment",
    //       replies: [
    //         {
    //           id: "dsds_asdAQ",
    //           username: "4-1Georrge random",
    //           avatar: "image-george.jpg",
    //           user_id: "@george.johnson",
    //           comment: "this is another  comment comment",
    //         },
    //         {
    //           id: "dsds_asdbas",
    //           username: "4-1Georrge random",
    //           avatar: "image-george.jpg",
    //           user_id: "@george.johnson",
    //           comment: "this is another  comment comment",
    //         },
    //         {
    //           id: "dsds_asdvbA",
    //           username: "4-2james dulex",
    //           avatar: "image-james.jpg",
    //           user_id: "@james.christina",
    //           comment: "comment comment comment",
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   id: "What_acxvDaaSda",
    //   username: "jay",
    //   link: "6_tags_for_solutions",
    //   title: "6 tags for solutions",
    //   detail: "Easier to search for solutions based on a specific stack.",
    //   category: "Bug",
    //   vote: 75,
    //   voted: false,
    //   status: "live",
    //   comments: [],
    // },
    // {
    //   id: "What_agds4aSda",
    //   username: "sb",
    //   link: "This_is_not_my_post",
    //   title: "This is not my post",
    //   detail: "Easier to search for solutions based on a specific stack.",
    //   category: "Feature",
    //   vote: 23,
    //   voted: false,
    //   status: "suggestion",
    //   comments: [],
    // },
    // {
    //   id: "What_ag88da",
    //   username: "jay",
    //   link: "7_tags_for_solutions",
    //   title: "7 tags for solutions",
    //   detail: "Easier to search23322 for solutions based on a specific stack.",
    //   category: "Feature",
    //   vote: 82,
    //   voted: false,
    //   status: "planned",
    //   comments: [],
    // },
  ],
};
